import { StyleSheet, Platform } from 'react-native';

let topSpace = 0
if(Platform.OS === 'ios'){
    topSpace = 40
}
else if(Platform.OS === 'android')
{
    topSpace = 0
} 
else
{
    topSpace = 0
}
export const BaseStyle = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: topSpace
  },
  light: {
    backgroundColor: '#b8cce0ff',
  },
  dark: {
    backgroundColor: '#181a20',
  },
  navBarGradient: {
    borderRadius: 10,
    marginBottom: 18,
    elevation: 2,
  },
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 10,
    marginBottom: 0,
    elevation: 0,
  },
  appNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appName: {
    fontSize: 22,
    fontWeight: 'bold',
    letterSpacing: 1,
    marginLeft: 6,
  },
  navLinks: {
    flexDirection: 'row',
  },
  navLink: {
    fontSize: 17,
    fontWeight: '500',
    marginHorizontal: 8,
  },
  navLinkActive: {
    color: '#007AFF',
    textDecorationLine: 'underline',
  },
  header: {
    fontSize: 15,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#222',
    letterSpacing: 1,
    textAlign: 'center',
  },
  summary: {
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  summaryText: {
    fontSize: 18,
    color: '#444',
  },
  count: {
    fontWeight: 'bold',
    color: '#007AFF',
  },
  addButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    shadowColor: '#007AFF',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  addButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  headerContainer: {
    margin: 20,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  }
});


export const lightTheme = {
  gradient: ["#a3d5e8", "#5a9fc4", "#2d5f8d", "#1e3a5f"],
  card: {
    backgroundColor: "#fff",
    borderColor: "#e5e7eb",
    borderWidth: 1,
    shadowColor: "#007AFF",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  header: {
    color: "#007AFF",
    textShadowColor: "#e3eafc",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  button: {
    backgroundColor: "#00ffd57e",
  },
  buttonText: {
    color: "#33fd00ff",
  },
  addButton: {
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 30,
    margin: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 0,
    shadowColor: "rgba(0, 0, 0, 0.3)",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 6,
  },
  addButtonText: {
    fontWeight: "800",
    fontSize: 18,
    letterSpacing: 1,
    textAlign: "center",
    color: "#2d5f8d",
  },

  greeting: {
    fontSize: 28,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 4,
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.9)",
    fontWeight: "500",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
    marginTop: 8,
  },
  statCard: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 16,
    padding: 20,
    flex: 1,
    marginHorizontal: 4,
    alignItems: "center",
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  statEmoji: {
    fontSize: 32,
    marginBottom: 8,
  },
  statNumber: {
    fontSize: 28,
    fontWeight: "800",
    color: "#2563eb",
    marginBottom: 4,
  },
  appName: {
    fontSize: 24,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 4,
    letterSpacing: 1,
  },
  statLabel: {
    fontSize: Platform.OS === "web" ? 14 : 12,
    color: "#64748b",
    fontWeight: "600",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 8,
    marginTop: 0,
  },
  deviceCard: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#94a3b8",
    shadowColor: "rgba(0, 0, 0, 0.15)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  deviceName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
  },
  deviceStatus: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
    fontWeight: "500",
  },
  deviceStatLabel: {
    fontSize: 11,
    color: "#94a3b8",
    marginBottom: 4,
    fontWeight: "600",
  },
  deviceStatValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#2563eb",
  },
  lastUpdated: {
    fontSize: 11,
    color: "#9e9e9e",
    marginTop: 12,
    fontStyle: "italic",
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 6,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.85)",
    textAlign: "center",
    fontWeight: "500",
  },
  floatingButton: {
    position: "absolute",
    bottom: 30,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    //backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    //shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  themeToggle: {
    position: "absolute",
    top: 60,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    //backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    //shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
};

export const darkTheme = {
    gradient: ['#000000', '#0d0d0f', '#1a1a1d'],
    card: {
        backgroundColor: '#23262f',
        borderColor: '#333',
        borderWidth: 1,
        shadowColor: '#fff',
        shadowOpacity: 0.18,
        shadowRadius: 8,
        elevation: 4,
    },
    header: {
        color: '#fff',
        textShadowColor: '#23262f',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 6,
    },
    button: {
        backgroundColor: 'black',
    },
    buttonText: {
        color: '#fff',
    },
     addButton: {
            paddingVertical: 16,
            paddingHorizontal: 40,
            borderRadius: 30,
            margin: 10,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: "#1f1f23",
            borderWidth: 0,
            shadowColor: "#000000",
            shadowOffset: { width: 0, height: 6 },
            shadowOpacity: 0.5,
            shadowRadius: 12,
            elevation: 6,
        },
        addButtonText: {
            fontWeight: '800',
            fontSize: 18,
            letterSpacing: 1,
            textAlign: 'center',
            color: "#ffffff",
        },
        
       
        greeting: {
            fontSize: 32,
            fontWeight: '800',
            color: "#ffffff",
            marginBottom: 4,
            textAlign: "center",
            textShadowColor: "rgba(0, 0, 0, 0.5)",
            textShadowOffset: { width: 0, height: 2 },
            textShadowRadius: 4,
        },
        subtitle: {
            fontSize: 16,
            color: "#a1a1aa",
            marginBottom: 20,
            textAlign: "center",
            fontWeight: "500",
        },
        statsContainer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 20,
        },
        statCard: {
            backgroundColor: "rgba(24, 24, 27, 0.72)",
            borderRadius: 16,
            padding: 18,
            flex: 1,
            marginHorizontal: 4,
            alignItems: 'center',
            borderWidth: 1,
            borderColor: "rgba(255, 255, 255, 0.12)",
            shadowColor: "#000000",
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.5,
            shadowRadius: 8,
            elevation: 4,
        },
        statNumber: {
            fontSize: 28,
            fontWeight: '800',
            color: "#ffffff",
            marginBottom: 4,
        },
        statLabel: {
            fontSize: Platform.OS === "web" ? 14 : 12,
            color: "#a1a1aa",
            fontWeight: "600",
        },
        sectionTitle: {
            fontSize: 22,
            fontWeight: "800",
            color: "#ffffff",
            marginBottom: 16,
            marginTop: 8,
            borderBottomWidth: 1,
            borderBottomColor: "#000000",
            paddingBottom: 8,
        },
        deviceCard: {
            backgroundColor: "rgba(24, 24, 27, 0.85)",
            borderWidth: 1,
            borderColor: "rgba(255, 255, 255, 0.14)",
            shadowColor: "#000000",
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.5,
            shadowRadius: 12,
            elevation: 6,
        },
        deviceName: {
            fontSize: 20,
            fontWeight: "800",
            color: "#ffffff",
        },
        deviceStatus: {
            fontSize: 13,
            color: "#a1a1aa",
            marginTop: 2,
            fontWeight: "600",
        },
        deviceStatLabel: {
            fontSize: 12,
            color: "#71717a",
            marginBottom: 4,
            fontWeight: "600",
        },
        deviceStatValue: {
            fontSize: 20,
            fontWeight: "800",
            color: "#ffffff",
        },
        lastUpdated: {
            fontSize: 11,
            color: "#71717a",
            marginTop: 12,
            fontStyle: "italic",
        },
        emptyTitle: {
            fontSize: 22,
            fontWeight: "800",
            color: "#ffffff",
            marginBottom: 8,
            textAlign: "center",
        },
        emptySubtitle: {
            fontSize: 15,
            color: "#a1a1aa",
            textAlign: "center",
            fontWeight: "500",
        },
        floatingButton: {
            position: 'absolute',
            bottom: 30,
            right: 20,
            width: 56,
            height: 56,
            borderRadius: 28,
            //backgroundColor: colors.primary,
            alignItems: 'center',
            justifyContent: 'center',
            //shadowColor: colors.primary,
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 8,
        },
        themeToggle: {
            position: 'absolute',
            top: 60,
            right: 20,
            width: 40,
            height: 40,
            borderRadius: 20,
            //backgroundColor: colors.surface,
            alignItems: 'center',
            justifyContent: 'center',
            //shadowColor: colors.shadow,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
            elevation: 4,
        },
};