import { StyleSheet } from 'react-native';

export const makeDedicatedIEControlStyles = (t) => StyleSheet.create({
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
    padding: 16,
  },
  card: {
    width: 240,
    padding: 16,
    margin: 8,
    backgroundColor: t.card,
    borderColor: t.cardBorder,
    borderWidth: 1,
    borderRadius: 12,
    shadowColor: t.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  channelText: {
    fontSize: 20,
    color: t.textPrimary,
    fontWeight: "bold",
    marginBottom: 8,
  },
  stateText: {
    fontSize: 16,
    textAlign: "center",
    color: t.textPrimary,
    fontWeight: "bold",
    marginBottom: 8,
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    margin: 16,
  },
  switchLabel: {
    fontSize: 14,
    color: t.textPrimary,
    marginHorizontal: 8,
  },
  errorText: {
    fontSize: 20,
    color: t.textOnGradient,
    fontWeight: "800",
    margin: 8,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  loadingCard: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 32,
    paddingHorizontal: 36,
    borderRadius: 24,
    minWidth: 250,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderLeftWidth: 3,
    borderLeftColor: "rgba(56, 189, 248, 0.75)",
    shadowColor: "#020617",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    elevation: 10,
  },
  loadingIconWrap: {
    width: 88,
    height: 88,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  loadingHalo: {
    position: "absolute",
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "rgba(56, 189, 248, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.45)",
  },
  loadingTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: t.textOnGradient,
    letterSpacing: 0.3,
    marginBottom: 6,
    textAlign: "center",
    textShadowColor: "rgba(15, 23, 42, 0.4)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  loadingSubtitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.78)",
    textAlign: "center",
  },
  loadingDotsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 18,
    gap: 8,
  },
  loadingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#38bdf8",
  },
  groupContainer: {
    margin: 8,
  },
  machineText: {
    fontSize: 22,
    color: t.textOnGradient,
    fontWeight: "800",
    marginBottom: 16,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  flexWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  controlsWrapper: {
    position: "relative",
  },
  blurredControls: {
    opacity: 0.3,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: t.scrim,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
  },
  overlayContent: {
    backgroundColor: t.overlayCard,
    borderWidth: 1,
    borderColor: t.overlayCardBorder,
    padding: 24,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: t.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  overlayText: {
    fontSize: 24,
    fontWeight: "bold",
    color: t.overlayTitle,
    marginBottom: 8,
    textAlign: "center",
  },
  overlaySubtext: {
    fontSize: 16,
    color: t.overlaySubtext,
    textAlign: "center",
  },
  buttonWrapper: {
    marginVertical: 8,
    marginHorizontal: 4,
    flexDirection: 'row',
    flexWrap: "wrap",
    justifyContent: 'center',
  },
  deviceButton: {
    backgroundColor: '#2d5f8d',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    width: 150,
    height: 150,
    margin: 10,
  },
  deviceButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
    textAlign: 'center',
    marginTop: 50,
  },
  fullOperationButton: {
    backgroundColor: '#2d5f8d',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    width: 100,
    height: 50,
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  /** Modern gradient pill buttons — work on both light & dark gradients */
  opButton: {
    minWidth: 140,
    height: 56,
    margin: 10,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#020617',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  opButtonLight: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.55)',
  },
  opButtonDark: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.16)',
  },
  opButtonDisabled: {
    opacity: 0.45,
  },
  opButtonGradient: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  opButtonIcon: {
    marginRight: 8,
  },
  opButtonText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
});
