import { StyleSheet } from 'react-native';

export const colors = {
  light: {
    primary: '#6200EE',
    secondary: '#03DAC6',
    background: '#d33b3bff',
    surface: '#F5F5F5',
    card: '#FFFFFF',
    text: '#df3232ff',
    textSecondary: '#666666',
    accent: '#FF6B35',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    shadow: 'rgba(0,0,0,0.1)',
    overlay: 'rgba(0,0,0,0.5)',
  },
  dark: {
    primary: '#BB86FC',
    secondary: '#03DAC6',
    background: '#121212',
    surface: '#1E1E1E',
    card: '#2C2C2C',
    text: '#FFFFFF',
    textSecondary: '#AAAAAA',
    accent: '#FF6B35',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#CF6679',
    shadow: 'rgba(255,255,255,0.1)',
    overlay: 'rgba(255,255,255,0.1)',
  },
};

export const homeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    paddingTop: 8,
    paddingBottom: 36,
  },
  gradient: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  /** Groups main blocks on the gradient with clear visual hierarchy */
  contentSection: {
    marginBottom: 20,
    padding: 14,
    borderRadius: 20,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderLeftWidth: 3,
    borderLeftColor: 'rgba(56, 189, 248, 0.75)',
    shadowColor: '#020617',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 8,
    overflow: 'hidden',
  },
  contentSectionActions: {
    borderLeftColor: 'rgba(52, 211, 153, 0.85)',
  },
  contentSectionDevices: {
    borderLeftColor: 'rgba(167, 139, 250, 0.9)',
  },
  /** Same shell as contentSection so the hero reads as the first panel, not a different UI */
  headerUnifiedCard: {
    width: '100%',
    marginBottom: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderStyle: 'solid',
    borderLeftWidth: 3,
    borderLeftColor: 'rgba(56, 189, 248, 0.75)',
    backgroundColor: 'transparent',
    paddingVertical: 14,
    paddingHorizontal: 14,
    shadowColor: '#020617',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 8,
    overflow: 'hidden',
  },
  headerSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    width: '100%',
  },
  headerGreetingColumn: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
    justifyContent: 'center',
  },
  greetingStack: {
    width: '100%',
  },
  headerColumnDivider: {
    width: 1,
    alignSelf: 'stretch',
    minHeight: 72,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    marginHorizontal: 10,
  },
  greetingIconSlot: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    flexShrink: 0,
  },
  greetingSciFiIconBubble: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.45)',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    shadowColor: '#38bdf8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },
  greetingTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  greetingAccentLine: {
    height: 2,
    borderRadius: 1,
    backgroundColor: 'rgba(56, 189, 248, 0.35)',
    marginVertical: 10,
    marginLeft: 50,
    marginRight: 4,
  },
  homeGreetingText: {
    textAlign: 'left',
    flexShrink: 1,
    fontSize: 30,
    letterSpacing: 0.4,
    textShadowColor: 'rgba(15, 23, 42, 0.35)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  subtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  homeSubtitleText: {
    textAlign: 'left',
    flexShrink: 1,
    fontSize: 15,
    lineHeight: 22,
    color: 'rgba(255, 255, 255, 0.92)',
    fontWeight: '500',
    textShadowColor: 'rgba(15, 23, 42, 0.25)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  headerBrokerColumn: {
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: '44%',
  },
  connectionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(241, 245, 249, 0.92)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.32)',
    borderStyle: 'solid',
    minWidth: 148,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  connectionIconBubble: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: '#f1f5f9',
  },
  connectionIconBubbleOk: {
    backgroundColor: 'rgba(5, 150, 105, 0.12)',
  },
  connectionIconBubblePending: {
    backgroundColor: 'rgba(217, 119, 6, 0.14)',
  },
  connectionIconBubbleErr: {
    backgroundColor: 'rgba(220, 38, 38, 0.1)',
  },
  connectionBadgeTextBlock: {
    flexShrink: 1,
  },
  connectionText: {
    fontSize: 15,
    fontWeight: '700',
  },
  connectionSubtext: {
    fontSize: 11,
    color: '#475569',
    fontWeight: '700',
    marginTop: 2,
    letterSpacing: 0.2,
  },
  actionCardGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
  },
  deviceCardGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
  },
  overviewCard: {
    backgroundColor: 'transparent',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: 'rgba(100, 116, 139, 0.35)',
    borderStyle: 'solid',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    overflow: 'hidden',
  },
  actionCardBody: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  deviceCardBody: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
  },
  overviewHeader: {
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(71, 85, 105, 0.22)',
    borderStyle: 'solid',
  },
  overviewTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  overviewTitleIconOrb: {
    width: 40,
    height: 40,
    borderRadius: 12,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(59, 130, 246, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.45)',
    shadowColor: '#1d4ed8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  overviewTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: 0.15,
    flex: 1,
  },
  overviewHint: {
    fontSize: 12,
    lineHeight: 18,
    color: '#475569',
    fontWeight: '600',
  },
  overviewStatsBand: {
    marginTop: 6,
    marginHorizontal: -16,
    marginBottom: -14,
    paddingTop: 10,
    paddingBottom: 12,
    paddingHorizontal: 16,
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
    overflow: 'hidden',
  },
  overviewStats: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    paddingTop: 0,
  },
  overviewStatItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    minHeight: 72,
  },
  overviewStatLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginBottom: 6,
    gap: 6,
  },
  overviewStatIconOrb: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(2, 132, 199, 0.45)',
    backgroundColor: 'rgba(14, 165, 233, 0.16)',
  },
  overviewStatIconOrbAlt: {
    borderColor: 'rgba(109, 40, 217, 0.45)',
    backgroundColor: 'rgba(167, 139, 250, 0.18)',
  },
  overviewStatNumber: {
    fontSize: 30,
    fontWeight: '800',
    color: '#1d4ed8',
    lineHeight: 34,
    marginTop: 2,
  },
  overviewStatLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#1e293b',
    fontWeight: '700',
    textAlign: 'center',
    flexShrink: 1,
    maxWidth: 130,
  },
  overviewDivider: {
    width: 1,
    alignSelf: 'stretch',
    minHeight: 56,
    backgroundColor: 'rgba(100, 116, 139, 0.4)',
    marginHorizontal: 8,
    marginVertical: 4,
    borderRadius: 1,
  },
  summary: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 24,
    marginBottom: 32,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 0,
  },
  actionButtonCardWrap: {
    flex: 1,
    minWidth: 0,
  },
  actionButtonCard: {
    flex: 1,
    minHeight: 156,
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  actionIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  actionIconWrapPrimary: {
    backgroundColor: 'rgba(45, 212, 191, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(13, 148, 136, 0.55)',
    shadowColor: '#0d9488',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 4,
  },
  actionIconWrapSecondary: {
    backgroundColor: 'rgba(96, 165, 250, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.5)',
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  actionButtonTitle: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 0.15,
  },
  actionButtonHint: {
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    fontWeight: '400',
    paddingHorizontal: 2,
  },
  primaryButton: {
    backgroundColor: 'transparent',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(45, 212, 191, 0.4)',
    borderLeftWidth: 4,
    borderLeftColor: '#0d9488',
    borderStyle: 'solid',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.4)',
    borderLeftWidth: 4,
    borderLeftColor: '#2563eb',
    borderStyle: 'solid',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  actionPrimaryHover: {
    borderColor: 'rgba(13, 148, 136, 0.72)',
    shadowColor: '#0d9488',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 7,
  },
  actionPrimaryPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.985 }],
    shadowOpacity: 0.06,
  },
  actionSecondaryHover: {
    borderColor: 'rgba(37, 99, 235, 0.65)',
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 7,
  },
  actionSecondaryPressed: {
    opacity: 0.94,
    transform: [{ scale: 0.985 }],
    shadowOpacity: 0.06,
  },
  actionCardTitle: {
    color: '#0f172a',
    fontWeight: '800',
  },
  actionCardHint: {
    color: '#475569',
    fontWeight: '600',
  },
  devicesSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 0,
  },
  devicesSectionHeaderInPanel: {
    paddingBottom: 12,
    marginBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.28)',
  },
  devicesSectionHeaderIcon: {
    marginRight: 10,
  },
  /** Same clarity idea as greeting: bright label + light shadow on dark glass */
  devicesSectionTitle: {
    marginBottom: 0,
    flexShrink: 1,
    color: 'rgba(255, 255, 255, 0.98)',
    fontWeight: '800',
    fontSize: 18,
    letterSpacing: 0.3,
    textShadowColor: 'rgba(15, 23, 42, 0.55)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  deviceListContainer: {
    marginTop: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  deviceCardWrap: {
    width: '48%',
    maxWidth: '48%',
    flexGrow: 0,
    flexShrink: 0,
  },
  /** Fill the wrap — do not use % width here (was 40% of 40% of row, crushing layout) */
  deviceCard: {
    width: '100%',
    alignSelf: 'stretch',
    backgroundColor: 'transparent',
    overflow: 'hidden',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 10,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: 'rgba(100, 116, 139, 0.38)',
    borderStyle: 'solid',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  deviceCardHover: {
    borderColor: 'rgba(59, 130, 246, 0.55)',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  deviceCardHoverLift: {
    transform: [{ scale: 1.02 }],
  },
  deviceCardPressed: {
    transform: [{ scale: 0.98 }],
    shadowOpacity: 0.06,
    opacity: 0.96,
  },
  deviceCardMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  deviceCardLeftZone: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    minWidth: 0,
  },
  deviceCardRightZone: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    minWidth: 0,
  },
  deviceCardChannelsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  deviceCardChevron: {
    marginLeft: 6,
    flexShrink: 0,
  },
  deviceCardNameText: {
    flexShrink: 1,
    minWidth: 0,
  },
  deviceCardNameInline: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
  },
  deviceNameChannelSep: {
    width: 1,
    height: 32,
    backgroundColor: 'rgba(148, 163, 184, 0.55)',
    marginHorizontal: 10,
    flexShrink: 0,
  },
  deviceIcon: {
    fontSize: 26,
    marginRight: 8,
    fontWeight: '800',
    color: '#1e3a8a',
    backgroundColor: 'rgba(191, 219, 254, 0.92)',
    width: 54,
    height: 54,
    borderRadius: 27,
    textAlign: 'center',
    lineHeight: 54,
    overflow: 'hidden',
    flexShrink: 0,
  },
  deviceChannelEmojiWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
    flexShrink: 0,
    backgroundColor: 'rgba(99, 102, 241, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(67, 56, 202, 0.45)',
  },
  deviceChannelLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1e293b',
    letterSpacing: 0.15,
    marginRight: 0,
    flexShrink: 0,
  },
  deviceChannelCount: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1d4ed8',
    marginLeft: 5,
    fontVariant: ['tabular-nums'],
  },
  deviceCardUpdated: {
    marginTop: 8,
    textAlign: 'left',
    fontStyle: 'normal',
    fontSize: 12,
    color: '#64748b',
    fontWeight: '600',
  },
  chevron: {
    fontSize: 24,
    color: '#94a3b8',
    fontWeight: '300',
  },
  deviceStat: {
    alignItems: 'flex-start',
  },
  activeStatValue: {
    color: '#2563eb',
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(100, 116, 139, 0.35)',
    overflow: 'hidden',
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateSubtitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
    textAlign: 'center',
    lineHeight: 21,
  },
  emptyStateIconRing: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'rgba(125, 211, 252, 0.45)',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    shadowColor: '#7dd3fc',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 4,
  },
  createButton: {
    backgroundColor: '#4285F4',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    marginTop: 20,
    minWidth: 200,
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  createButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
});
